const { NOUNS, ADJECTIVES, NAMES, MILLION_PASSWORD, HUNDRED_PASSWORD } = require('./filesName');
const { NUMBER_OF_PASSWORDS, PASSWORD_LENGTH, MIN_PASSWORD_LENGTH } = require('./passwordProperties');
const { MILLION_POPULAR_PASSWORD, HUNDRED_POPULAR_PASSWORD, HUMAM_PASSWORD } = require('./percent');

module.exports = {
    NOUNS, 
    ADJECTIVES, 
    NAMES, 
    MILLION_PASSWORD, 
    HUNDRED_PASSWORD,
    NUMBER_OF_PASSWORDS, 
    PASSWORD_LENGTH,
    MILLION_POPULAR_PASSWORD, 
    HUNDRED_POPULAR_PASSWORD, 
    HUMAM_PASSWORD,
    MIN_PASSWORD_LENGTH
}