const MILLION_POPULAR_PASSWORD = 0.7;
const HUNDRED_POPULAR_PASSWORD = 0.95;
const HUMAM_PASSWORD = 0.85;

module.exports = {
    MILLION_POPULAR_PASSWORD,
    HUNDRED_POPULAR_PASSWORD,
    HUMAM_PASSWORD
};